### ISSUE TITLE
NYPL Welcomes Your Help

### ISSUE THREAD

**Issue by gregcram** [EbookFoundation/capstone-projects#1]
On behalf of NYPL, I look forward to working with the team on this important and vital project. As NYPL's product owner for the Copyright Office Records project, I'm excited for this opportunity. I'll be watching the repo as it develops and am happy to answer any questions.

**Comment by eshellman** [comment]
It seems the team that had expressed interest in the copyright records search chose another project. I'm going to reach out to some other schools to see if there are similar programs.

**Comment by gregcram** [comment]
Thanks, Eric. Let me know if I can be of any help.

**Comment by Isnai789** [comment]
Saya menawarkan pinang dari aceh bagaimana ada yang minat di daerah anda

**Comment by Isnai789** [comment]
Ok Eric apa proyek yang bisa kita kerja kan
