### ISSUE TITLE
Looking for team - copyright record search system

### ISSUE THREAD

**Issue by villa7** [EbookFoundation/capstone-projects#2]
1 / 5 members for [copyright record search system](https://github.com/EbookFoundation/capstone-projects/blob/master/copyright-renewals.md)

- [x] Theodore Kluge  
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5

**Comment by eshellman** [comment]
There were a few students from the Monday class who were interested- hope you can form a team!
