### ISSUE TITLE
Team for Update Pipeline for E-book Authoring Systems project

### ISSUE THREAD

**Issue by maxmelo** [EbookFoundation/capstone-projects#3]
2/5 members:

- Max Melo
- Michael Iacona
- ?
- ?
- ?

**Comment by eshellman** [comment]
if you have any questions, ask them here!

**Comment by villa7** [comment]
I would like to join this team if I cannot get enough people for the other project

**Comment by ghowardsit** [comment]
totally in

**Comment by villa7** [comment]
Thats 5 👍

**Comment by villa7** [comment]
Thats 5 @maxmelo 👍 

**The deadline for choosing a team and a project is this Thursday, by noon for class members in CS423A and by 2:30 for those in CS423B.**  

will need: 
The name of the project
The name of the project client
The email address of the project client.
The phone number of the project client

The name of team member #n
The section of CS423 in which team member #n is registered, that is, CS423A or CS423B, , or the team member’s major, if it’s not CS.
The Stevens email address of team member #n
The outside (gmail, yahoo, etc.) email address of team member #n
The phone number of team member #n

Theres an email going around to collect contact info.

- [ ] Someone will need to fill out [this Google form](https://docs.google.com/forms/d/12ZvUGijDbTneMc-SjF7KCd3FYqLNEHfwwhQJsSfVPmU/viewform) with information about the group before then.
- [ ] Will also need to submit a PR with team info added to [this file](https://github.com/EbookFoundation/capstone-projects/blob/master/pipeline.md)

**Comment by eshellman** [comment]
That was fast!

**Comment by eshellman** [comment]
Have invited team members to the EbookFoundation github organization. Please turn on 2-factor authentication. Next week I am free anytime except Tue after 3 and Wed 11-2 if you want to set up a google hangout or similar.
