### ISSUE TITLE
User Demographics

### ISSUE THREAD

**Issue by vlee98** [EbookFoundation/capstone-projects#7]
Would you be able to provide a little more information about what types of devices the users of Gutenberg in a box would be using? 

For instance what would be the average year of a machine that would connect so we can get a gauge of how much ram they would have and which technologies would be suitable to pair.

**Comment by eshellman** [comment]
I don't have an answer handy, but this link may give you a better idea. http://wiki.laptop.org/go/IIAB/FAQ#Where_is_Internet-in-a-Box_used.3F

I'd expect lots of Android based smartphones and tablets, etc. I'm told that many OLPC laptops (from 2012 or earlier) are still in use, so many clients may be comparable to the XO laptop http://wiki.laptop.org/go/XO
